language: python

# python:
#   - "2.7"
#   - "3.3"

# env:
#   - NUMPY_VERSION=1.8
#   - NUMPY_VERSION=1.7
  
env:
  global:
    - SCIPY_VERSION=0.14
       
  
matrix:
    fast_finish: true
    include:
    - python: 2.7
      env:
      - PYTHON_VERSION=2.7
      - NUMPY_VERSION=1.7
      - JOB_NAME: "python_27_numpy_17"
    - python: 2.7
      env:
      - PYTHON_VERSION=2.7
      - NUMPY_VERSION=1.8
      - JOB_NAME: "python_27_numpy_18"
    - python: 2.7
      env:
      - PYTHON_VERSION=3.3
      - NUMPY_VERSION=1.7
      - JOB_NAME: "python_33_numpy_17"
    - python: 2.7
      env:
      - PYTHON_VERSION=3.3
      - NUMPY_VERSION=1.8
      - JOB_NAME: "python_33_numpy_18"
      
      
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
#   - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh; fi
#   - chmod +x miniconda.sh
  - bash miniconda.sh -b
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda update --quiet conda
  - conda info -a
  
  # Fix for headless TravisCI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - conda create -n testenv python=$PYTHON_VERSION numpy=$NUMPY_VERSION scipy=$SCIPY_VERSION matplotlib six pytest pip
  - source activate testenv
#   - conda install --yes 
  - pip install .
  - python setup.py install
  
script:
#   - python setup.py install
  - py.test