language: python

python:
  - 2.7
  - 3.4

env:
  global:
    - NUMPY_VERSION=1.9.1
    - SCIPY_VERSION=0.14
    - INSTALL_OPTIONAL=true

matrix:
  include:
    - python: 2.7
      env: NUMPY_VERSION=1.8.2
    - python: 3.4
      env: NUMPY_VERSION=1.8.2

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

  # Fix for headless TravisCI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY_VERSION scipy=$SCIPY_VERSION matplotlib six pytest pip cython numexpr
  - source activate testenv

  # Optional dependencies
  - if $INSTALL_OPTIONAL; then conda install --yes pandas=0.14.1; fi

  #- pip install .
  - python setup.py install

script:
  - py.test
